
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '896D50EBEE1837401888C402930B053A'
    
_lr_action_items = {'PRINT':([0,3,7,8,9,14,15,],[1,1,1,1,1,1,1,]),'VAR':([0,3,7,8,9,14,15,],[3,3,3,3,3,3,3,]),'$end':([2,4,5,6,13,16,17,18,],[0,-7,-5,-6,-3,-1,-4,-2,]),'NUM':([0,3,7,8,9,14,15,],[4,4,4,4,4,4,4,]),'LPAREN':([1,],[8,]),'TEXT':([0,3,7,8,9,14,15,],[5,5,5,5,5,5,5,]),'RPAREN':([4,5,6,12,13,16,17,18,],[-7,-5,-6,16,-3,-1,-4,-2,]),'SIMB':([0,3,7,8,9,14,15,],[6,6,6,6,6,6,6,]),'LET':([0,3,7,8,9,14,15,],[7,7,7,7,7,7,7,]),'=':([2,4,5,6,10,11,12,13,16,17,18,],[9,-7,-5,-6,14,15,9,9,-1,9,9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'item':([0,3,7,8,9,14,15,],[2,10,11,12,13,17,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> item","S'",1,None,None,None),
  ('item -> PRINT LPAREN item RPAREN','item',4,'p_print','yacc.py',41),
  ('item -> LET item = item','item',4,'p_let','yacc.py',51),
  ('item -> item = item','item',3,'p_reassign','yacc.py',59),
  ('item -> VAR item = item','item',4,'p_var','yacc.py',68),
  ('item -> TEXT','item',1,'p_TEXT_item','yacc.py',72),
  ('item -> SIMB','item',1,'p_SIMB_item','yacc.py',76),
  ('item -> NUM','item',1,'p_NUM_item','yacc.py',80),
]
